version: '3'
services:
    web:
        build:
            context: ./app
            args:
                DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        restart: always
        expose:
            - "8000"
        ports:
            - "8000:8000"
        volumes:
            - ./db.sqlite3:/opt/app/db/db.sqlite3
            - ./data:/var/www/static
        environment:
            DJANGO_STATIC_ROOT: "/var/www/static"

     nginx:
        image: nginx
        restart: always
        volumes:
            - ./default.conf:/etc/nginx/templates/default.conf.template:ro
            - ./nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
            - ./nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro
            - ./dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
            - ./data:/var/www/static
        environment:
            - SERVER_NAME=$SERVER_NAME
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web
