# Generated by Django 2.2.4 on 2019-08-28 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('template_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_male', models.BooleanField(default=True)),
                ('tel_number', models.CharField(max_length=11)),
                ('rank', models.IntegerField()),
                ('position', models.CharField(max_length=500)),
                ('dept', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='pisar.Department')),
                ('supervisor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='pisar.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='chief',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='pisar.Employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='pisar.Department'),
        ),
    ]
