# Generated by Django 2.2.4 on 2019-09-05 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pisar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pisar.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel_number',
            field=models.CharField(max_length=15),
        ),
    ]
