# Generated by Django 2.2.4 on 2019-09-05 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pisar', '0002_auto_20190905_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='chief',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pisar.Employee'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pisar.Department'),
        ),
    ]
