# Generated by Django 2.2.4 on 2019-09-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pisar', '0003_auto_20190905_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='supervisor',
        ),
    ]
