# Generated by Django 2.1.2 on 2018-12-05 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_as_int', models.IntegerField()),
                ('mask_as_int', models.IntegerField()),
                ('gateway_as_int', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_root_segment', models.BooleanField(default=False)),
                ('parent_segment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_list.Segment')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('is_physical', models.BooleanField()),
                ('is_on', models.BooleanField()),
                ('os', models.CharField(blank=True, max_length=50)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('serial_num', models.CharField(blank=True, max_length=100)),
                ('specs', models.CharField(blank=True, max_length=200)),
                ('sensitive_data', models.CharField(blank=True, max_length=200)),
                ('height', models.IntegerField(default=1)),
                ('host_machine', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_list.Server')),
                ('segments', models.ManyToManyField(through='server_list.Ip', to='server_list.Segment')),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('rack', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_list.Rack')),
                ('server', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_list.Server')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_list.Territory'),
        ),
        migrations.AddField(
            model_name='rack',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_list.Room'),
        ),
        migrations.AddField(
            model_name='ip',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_list.Segment'),
        ),
        migrations.AddField(
            model_name='ip',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_list.Server'),
        ),
    ]
