# Generated by Django 2.1.2 on 2018-12-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='height',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
