# Generated by Django 2.1.5 on 2019-02-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='location',
            field=models.IntegerField(blank=True),
        ),
    ]
