# Generated by Django 2.1.5 on 2019-02-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0002_auto_20190225_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='location',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
