# Generated by Django 2.1.2 on 2018-12-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0002_auto_20181205_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
