# Generated by Django 2.1.2 on 2018-12-05 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0003_auto_20181205_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='server',
        ),
        migrations.AddField(
            model_name='server',
            name='unit',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_list.Unit'),
        ),
    ]
