# Generated by Django 2.1.4 on 2019-02-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0003_auto_20190225_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='rack',
        ),
        migrations.AddField(
            model_name='rack',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rack',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
