# Generated by Django 2.1.2 on 2018-12-18 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0004_auto_20181205_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='rack',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='server_list.Rack'),
        ),
        migrations.AlterField(
            model_name='server',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
