# Generated by Django 2.1.7 on 2019-04-10 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0005_auto_20190311_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='ip_as_int',
        ),
    ]
