# Generated by Django 2.1.7 on 2019-04-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0007_auto_20190412_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servergroup',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
