# Generated by Django 2.1.7 on 2019-02-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0002_rack_topdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='topdown',
            field=models.BooleanField(default=False),
        ),
    ]
