# Generated by Django 2.1.7 on 2019-03-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0003_auto_20190227_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='ip_as_string',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
