# Generated by Django 2.1.7 on 2019-03-11 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0004_ip_ip_as_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='server_list.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='territory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='server_list.Territory'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='parent_segment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server_list.Segment'),
        ),
        migrations.AlterField(
            model_name='server',
            name='host_machine',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server_list.Server'),
        ),
        migrations.AlterField(
            model_name='server',
            name='rack',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server_list.Rack'),
        ),
    ]
