# Generated by Django 2.1.7 on 2019-04-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0008_auto_20190412_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='hostname_lower',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='purpose_lower',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
