# Generated by Django 2.2.4 on 2019-08-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0009_auto_20190419_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='gateway_as_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ip',
            name='mask_as_int',
            field=models.IntegerField(default=0),
        ),
    ]
